include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint
  exclude: [lib/generated/**]
  errors:
    invalid_annotation_target: ignore
    
custom_lint:
  rules:
  - missing_provider_scope: false