name: weather_app
description: "Weather app for improving flutter skills"
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  dio: ^5.4.3+1
  easy_localization: ^3.0.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  freezed_annotation: ^2.4.1
  go_router: ^13.2.4
  hooks_riverpod: ^2.5.1
  json_annotation: ^4.8.1
  logger: ^2.2.0
  retrofit: ^4.1.0
  riverpod_annotation: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  test: ^1.24.9
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/image/flags/
