name: Deploy
run-name: ${{ github.actor }} Deploy 🚀

on:
  push:
    branches:
      - main

env:
  FLUTTER_VERSION: 3.22.0

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: ${{ env.FLUTTER_VERSION }}
  
      - name: Flutter info
        run: flutter --version && flutter pub get

      - name: Codogen
        run: bash scripts/codogen.sh 

      - name: Build web
        run: flutter build web --release --base-href="/weather_app/"

      - name: Deploy web
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
