name: Push job
run-name: Push job
on: [push]
jobs:
  Flutter_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.5
  
      - name: Flutter info
        run: flutter --version && flutter pub get

      - name: Lint
        run: bash scripts/lint.sh

